# Install Nginx on Ubuntu
---
- name: Install Nginx and enable it
  hosts: host1
  become: True
  tasks:
  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: Start the Nginx Service
    service:
      name: nginx
      state: started

  - name: Enable the Nginx Service
    service:
      name: nginx
      enabled: True

  - name: Get Nginx installed version
    command: nginx -v

  - name: Get status of Nginx Service
    command: systemctl status nginx
